routes/admin.php
<?php

Route::get('/home', function () {
    $users[] = Auth::user();
    $users[] = Auth::guard()->user();
    $users[] = Auth::guard('admin')->user();

    //dd($users);

    return view('admin.home');
})->name('home');

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});


Route::view('test','tutor.QR');

Route::group(['prefix' => 'admin'], function () {
    Route::group(['middleware'=>'admin'],function (){
    Route::get('/','AdminPanel\AdminController@index')->name('index');
    Route::resource('student','AdminPanel\studentController');
    Route::resource('tutor','AdminPanel\tutorController');
    Route::resource('admin','AdminPanel\adminUserController');
    Route::resource('lab','AdminPanel\labController');
    Route::post('/password/{id}','AdminPanel\studentController@updatePassword')->name('updatePassword');
    Route::post('/admin/password/{id}','AdminPanel\adminUserController@updatePassword')->name('adminUpdatePassword');
    Route::get('/attend/{id}','AdminPanel\sessionController@attends')->name('attendBySession');
    Route::get('student/attend/{id}','AdminPanel\studentController@attends')->name('studentAttend');
    Route::get('lab/session/{id}','AdminPanel\labController@session')->name('sessionLab');
    Route::get('tutor/session/{id}','AdminPanel\tutorController@session')->name('tutorSession');
    Route::resource('session','AdminPanel\sessionController');
    Route::get('student/MAC/{id}','AdminPanel\studentController@resethMAC')->name('studentMAC');
    Route::get('tutor/MAC/{id}','AdminPanel\tutorController@resetMAC')->name('tutorMAC');

    });


    Route::get('/login', 'AdminAuth\LoginController@showLoginForm')->name('login');
    Route::post('/login', 'AdminAuth\LoginController@login');
    Route::post('/logout', 'AdminAuth\LoginController@logout')->name('logout');
 /*   Route::get('/register', 'AdminAuth\RegisterController@showRegistrationForm')->name('register');
    Route::post('/register', 'AdminAuth\RegisterController@register');*/
    Route::post('/password/email', 'AdminAuth\ForgotPasswordController@sendResetLinkEmail')->name('password.request');
    Route::post('/password/reset', 'AdminAuth\ResetPasswordController@reset')->name('password.email');
    Route::get('/password/reset', 'AdminAuth\ForgotPasswordController@showLinkRequestForm')->name('password.reset');
    Route::get('/password/reset/{token}', 'AdminAuth\ResetPasswordController@showResetForm');
});

Route::group(['middleware'=>'auth:web'],function (){
Route::get('Qr','Qr@index');
Route::get('Qr/session/{id}','Qr@Qr')->name('QR');
Route::get('Qr/refresh/{id}','Qr@refresh')->name('QrRefresh');
});
Route::view('notTutor','tutor.ForTutorOnly');
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

Route::get('/home', 'HomeController@index')->name('home');

app/Http/Controllers/AdminPanel/AdminController.php
<?php

namespace App\Http\Controllers\AdminPanel;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class AdminController extends Controller
{
    public function index()
    {
        return view('adminPanel.index');
    }
}

app/Http/Controllers/AdminPanel/adminUserController.php
<?php

namespace App\Http\Controllers\AdminPanel;

use Alert;
use App\Admin;
use App\Http\Controllers\Controller;
use App\Http\Requests\addAdmin;
use App\Http\Requests\updatePassword;
use Illuminate\Http\Request;

class adminUserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('adminPanel.admin.index')->with('admins',Admin::all());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('adminPanel.admin.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(addAdmin $request)
    {
        Admin::create($request->except('password') + ['password'=>bcrypt($request['password'])]);
        alert()->success('Success Message')->autoclose(1000);
        return back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return view('adminPanel.admin.edit')->with('admin',Admin::where('id',$id)->first());
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $user=Admin::where('id',$id)->first();
        $user->update($request->only('name'));
        alert()->success('Success Message')->autoclose(1000);
        return back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function updatePassword(updatePassword $request,$id)
    {
        $user = Admin::where('id', $id)->first();
        $user->update(['password' => bcrypt($request['password'])]);
        Alert::success('Password Edified Successfully !')->persistent('Close');
        return back();
    }

}

app/Http/Controllers/AdminPanel/labController.php
<?php

namespace App\Http\Controllers\AdminPanel;

use App\Http\Controllers\Controller;
use App\Http\Requests\labAdd;
use App\Location;
use Illuminate\Http\Request;
use App\Session;

class labController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('adminPanel.lab.index')->with('labs', Location::all());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('adminPanel.lab.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(labAdd $request)
    {
        Location::create($request->all());
        alert()->success('Success Message', 'Optional Title')->autoclose(1000);
        return back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return view('adminPanel.lab.show')->with('lab',Location::find($id));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return view('adminPanel.lab.edit')->with('lab',Location::find($id));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(labAdd $request, $id)
    {
        Location::find($id)->update($request->all());
        alert()->success('Success Message', 'Optional Title')->autoclose(1000);
        return back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function session($id){
        return view('adminPanel.session.index')->with('sessions',Session::with('lab','doctor')->where('labID',$id)->get());
    }
}

app/Http/Controllers/AdminPanel/sessionController.php
<?php

namespace App\Http\Controllers\AdminPanel;

use App\Attend;
use App\Http\Controllers\Controller;
use App\Session;
use Illuminate\Http\Request;

class sessionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('adminPanel.session.index')->with('sessions',Session::with('lab','doctor')->get());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return view('adminPanel.session.show')->with('session',Session::with('lab','doctor')->where('id',$id)->first());
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Session::find($id)->delete();
        alert()->success('Success Message', 'Optional Title')->autoclose(1000);
        return back();
    }

    public function attends($id)
    {
        return view('adminPanel.attends.index')->with('attends',Attend::where('SessionID',$id)->with('session')->get());
    }
}

app/Http/Controllers/AdminPanel/studentController.php
<?php

namespace App\Http\Controllers\AdminPanel;

use App\Attend;
use App\Http\Controllers\Controller;
use App\Http\Requests\addUser;
use App\Http\Requests\updatePassword;
use App\Http\Requests\updateUser;
use App\User;
use Token;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Input;
use LaravelImage\ImageUploadService;
use Alert;
class studentController extends Controller
{
    protected $file;

    /**
     * @param ImageUploadService $file
     */
    public function __construct(ImageUploadService $file)
    {

        //set properties for file upload
        $this->file = $file;
        $this->file->setUploadField('photo'); //default is image
        $this->file->setUploadFolder('students');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('adminPanel.student.index')->with('students',User::where('type',0)->get());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('adminPanel.student.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(addUser $request)
    {
        //dd($request->all());
       // dd(Token::Unique('users','api_token',100,true));
        $image='';
        if (Input::hasFile('photo') && $this->file->upload()) {
            $image = $this->file->getUploadedFileInfo()['upload_dir']. $this->file->getUploadedFileInfo()['photo'];
        }
        User::create($request->except('photo','password') + ['image'=>$image,
                'api_token'=>Token::Unique('users','api_token', 100,true ),'password'=>bcrypt($request['password']),
                'type'=>0]);

        alert()->success('Success Message', 'Optional Title')->autoclose(1000);
        return back();

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return view('adminPanel.student.show')->with('student',User::where('uuid',$id)->first());
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {

      //  dd(User::where('uuid',23423)->first());
        return view('adminPanel.student.edit')->with('student',User::where('uuid',$id)->first());
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(updateUser $request, $id)
    {
        $user=User::where('uuid',$id)->first();
        $image=$user->image;

        if (Input::hasFile('photo') && $this->file->upload()) {
            $image = $this->file->getUploadedFileInfo()['upload_dir']. $this->file->getUploadedFileInfo()['photo'];
        }
        $user->update($request->except('photo') + ['image'=>$image,
                'api_token'=>Token::Unique('users','api_token', 100,true ),
                'type'=>0]);

        alert()->success('Success Message', 'Optional Title')->autoclose(1000);
        return back();
    }

    /**
     * @param UpdatePassword $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function updatePassword(updatePassword $request,$id)
    {
        $user = User::where('uuid', $id)->first();
        $user->update(['password' => bcrypt($request['password'])]);
        Alert::success('Password Edified Successfully !')->persistent('Close');
        return back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        User::where('uuid',$id)->delete();
        Alert::success('User deleted Successfully !')->autoclose(1000);
        return back();
    }

    public function attends($id)
    {
       // dd(Attend::where('studentID',$id)->with('session')->get());
        return view('adminPanel.attends.index')->with('attends',Attend::where('studentID',$id)->with('session')->get());
    }

    public function resethMAC($id)
    {
        User::where('uuid',$id)->first()->update(['MAC'=>null]);
        Alert::success('MAC Reset Successfully !')->autoclose(1000);
        return back();
    }
}

resources/views/adminPanel/student/create.blade.php
@extends('adminPanel.layouts.main')
@section('content')
    <!-- ////////// Page Title & Breadcrumbs //////////-->
    <div class="row">
        <div class="col-xs col-sm-12 col-md-12 col-lg-12 col-xl-12">
            <h4>Students</h4>
            <nav class="breadcrumb">
                <a class="breadcrumb-item" href="#">Home</a>
                <a class="breadcrumb-item" href="{{route('student.index')}}">students</a>
                <span class="breadcrumb-item active">Add student</span>
            </nav> <!-- /breadcrumb -->
        </div> <!-- /col -->
    </div> <!-- /row -->

    <div class="row">

        <!-- ////////// Basic DataTable //////////-->
        <div class="col-xs col-sm-12 col-md-12 col-lg-12 col-xl-12 mt-4">

            @include('adminPanel.student.form')

        </div>
    </div>
@endsection

resources/views/adminPanel/student/edit.blade.php
@extends('adminPanel.layouts.main')
@section('content')
    <!-- ////////// Page Title & Breadcrumbs //////////-->
    <div class="row">
        <div class="col-xs col-sm-12 col-md-12 col-lg-12 col-xl-12">
            <h4>Users</h4>
            <nav class="breadcrumb">
                <a class="breadcrumb-item" href="#">Home</a>
                <a class="breadcrumb-item" href="{{route('student.index')}}">student</a>
                <span class="breadcrumb-item active">edit student</span>
            </nav> <!-- /breadcrumb -->
        </div> <!-- /col -->
    </div> <!-- /row -->

    <div class="row">

        <!-- ////////// Basic DataTable //////////-->
        <div class="col-xs col-sm-12 col-md-12 col-lg-12 col-xl-12 mt-4">

            @include('adminPanel.student.form')
        </div>
    </div>
@endsection

resources/views/adminPanel/student/form.blade.php
<div class="card">
    <div class="card-heading">
        <h5>student</h5>
    </div> <!-- /card-heading -->
    <div class="card-body">
        {!! Form::open(['url'=>isset($student)?route('student.update',['id'=>$student->uuid]):route('student.store'),'method'=> isset($student)?'put':'post','files'=>true]) !!}


        @if(!isset($student))
        <div class="form-group {{ $errors->has('uuid') ? ' has-error' : '' }}">
            <label for="example-name-input" class="form-label">ID</label>
            <input class="form-control" type="text" placeholder="ID" name="uuid"
                   value="{{isset($student)?$student->uuid:old("uuid")}}"
                   id="example-name-input">
            @component('adminPanel.layouts.errors')
                @slot('slot')
                    uuid
                @endslot
            @endcomponent
        </div>
        @endif
        <div class="form-group {{ $errors->has('name') ? ' has-error' : '' }}">
            <label for="example-name-input" class="form-label">Name</label>
            <input class="form-control" type="text" placeholder="Name" name="name"
                   value="{{isset($student)?$student->name:old("name")}}"
                   id="example-name-input">
            @component('adminPanel.layouts.errors')
                @slot('slot')
                    name
                @endslot
            @endcomponent
        </div> <!-- /form-group -->


        @if(!isset($student))
        <div class="form-group  {{ $errors->has('email') ? ' has-error' : '' }}">
            <label for="exampleInputEmail2">Email address</label>
            <input type="email" class="form-control" id="" name="email"
                   value="{{isset($student)?$student->email:old("email")}}"
                   placeholder="Enter email">
            @component('adminPanel.layouts.errors')
                @slot('slot')
                    email
                @endslot
            @endcomponent
        </div> <!-- /form-group -->
        @endif
        @if(!isset($student))
            <div class="row {{ $errors->has('password') ? ' has-error' : '' }}">
                <div class="col-xs col-sm-12 col-md-12 col-lg-6 col-xl-6">
                    <div class="form-group">
                        <label for="inputPassword3" class="form-label">Password</label>
                        <input type="password" class="form-control" id="inputPassword3"
                               name="password" placeholder="Password">
                    </div> <!-- /form-group -->
                </div> <!-- /col -->
                <div class="col-xs col-sm-12 col-md-12 col-lg-6 col-xl-6">
                    <div class="form-group">
                        <label for="inputConfrimPassword3" class="form-label">Confrim Password</label>
                        <input type="password" class="form-control" id="inputConfrimPassword3"
                               name="password_confirmation" placeholder="Confrim Password">
                    </div> <!-- /form-group -->
                </div> <!-- /col -->
                @component('adminPanel.layouts.errors')
                    @slot('slot')
                        password
                    @endslot
                @endcomponent
            </div> <!-- /row -->
        @endif
        <div class="form-group">
            <label for="example-text-input" class="form-label">Phone</label>
            <input class="form-control" type="text" name="phone" placeholder="phone"
                   value="{{isset($student)?$student->phone:old("phone")}}" id="example-text-input">
            @component('adminPanel.layouts.errors')
                @slot('slot')
                    phone
                @endslot
            @endcomponent
        </div> <!-- /form-group -->

        <div class="form-group">

            @if(isset($student))
                {!! Html::image($student->image,'',['class'=>'img-responsive','width'=>'300px','height'=>'300px']) !!}
            @endif
        </div>
        <div class="form-group  {{ $errors->has('photo') ? ' has-error' : '' }}">
            <label class="form-label"> Profile Picture</label>
            <div class="input-group file-upload">
                <label class="custom-file pull-left">
                    <input type="file" id="file" name="photo" class="custom-file-input">
                    <span class="custom-file-control"></span>
                </label> <!-- /custom-file -->
                @component('adminPanel.layouts.errors')
                    @slot('slot')
                        photo
                    @endslot
                @endcomponent
            </div> <!-- /form-group -->
        </div>


        <button type="submit" class="btn btn-primary pull-right">Submit</button>
    {!! Form::close() !!} <!-- /form -->
    </div>
    <div class="card-body">

    </div>
</div>


@if(isset($student))
    <br>
    <div class="card">
        <div class="card-heading">
            <h5>Update student Password <i class="fa fa-pencil"></i></h5>
        </div> <!-- /card-heading -->
        <div class="card-body">
            {!! Form::open(['url'=>route('updatePassword',['id'=>$student->uuid]),'method'=> 'post']) !!}
            <div class="row {{ $errors->has('password') ? ' has-error' : '' }}">
                <div class="col-xs col-sm-12 col-md-12 col-lg-6 col-xl-6">
                    <div class="form-group">
                        <label for="inputPassword3" class="form-label">Password</label>
                        <input type="password" class="form-control" id="inputPassword3"
                               name="password" placeholder="Password">
                    </div> <!-- /form-group -->
                </div> <!-- /col -->
                <div class="col-xs col-sm-12 col-md-12 col-lg-6 col-xl-6">
                    <div class="form-group">
                        <label for="inputConfrimPassword3" class="form-label">Confrim Password</label>
                        <input type="password" class="form-control" id="inputConfrimPassword3"
                               name="password_confirmation" placeholder="Confrim Password">
                    </div> <!-- /form-group -->
                </div> <!-- /col -->
                @component('adminPanel.layouts.errors')
                    @slot('slot')
                        password
                    @endslot
                @endcomponent
            </div> <!-- /row -->
            <button type="submit" class="btn btn-primary pull-right">Submit</button>
            {!! Form::close() !!}
        </div>
    </div>
    @endif

resources/views/adminPanel/student/index.blade.php
@extends('adminPanel.layouts.main')
@section('content')
    <!-- ////////// Page Title & Breadcrumbs //////////-->
    <div class="row">
        <div class="col-xs col-sm-12 col-md-12 col-lg-12 col-xl-12">
            <h4>students</h4>
            <nav class="breadcrumb">
                <a class="breadcrumb-item" href="#">Home</a>
                <span class="breadcrumb-item active">students</span>
            </nav> <!-- /breadcrumb -->
        </div> <!-- /col -->
    </div> <!-- /row -->

    <div class="row">

        <!-- ////////// Basic DataTable //////////-->
        <div class="col-xs col-sm-12 col-md-12 col-lg-12 col-xl-12 mt-4">
            <div class="card">
                <div class="card-heading">
                    <h5><a href="{{route('student.create')}}">Add new student <i class="fa fa-plus"></i></a></h5>
                </div> <!-- /card-heading -->
                <div class="card-body">

                    <table id="basic_table" class="table_top_content table table-responsive table-striped">
                        <thead>
                        <tr>
                            <th>ID</th>
                            <th>Name</th>
                            <th>Email</th>
                            <th>Phone</th>
                            <th>Created at</th>
                            <th>Action</th>
                        </tr> <!-- /tr -->
                        </thead> <!-- /thead -->
                        <tbody>
                        @foreach($students as $key=> $student)
                        <tr>
                            <td>{{$student->uuid}}</td>
                            <td>{{$student->name}}</td>
                            <td>{{$student->email}}</td>
                            <td>{{$student->phone}}</td>
                            <td>{{$student->created_at}}</td>
                            <td>
                                <a href="{{route('student.edit',['id'=>$student->uuid])}}"><i class="fa fa-pencil"></i></a>
                                &nbsp;
                                <a href="{{route('student.show',['id'=>$student->uuid])}}"><i class="fa fa-eye"></i> </a>
                                &nbsp;
                                <a onclick="$('#{{$key}}delete').submit()"><i class="fa fa-trash"></i> </a>
                                {!! Form::open(['url'=>route('student.destroy',['id'=>$student->uuid]),'method'=>'delete','id'=>$key.'delete']) !!}
                                {!! Form::close() !!}
                            </td>
                        </tr>
                        @endforeach

                        </tbody> <!-- /tbody -->
                        <tfoot>
                        <tr>
                            <th>Name</th>
                            <th>Email</th>
                            <th>Phone</th>
                            <th>Created at</th>
                            <th>Action</th>
                        </tr> <!-- /tr -->
                        </tfoot> <!-- /tfoot -->
                    </table> <!-- /table-responsive -->
                </div> <!-- /card-body -->
            </div> <!-- /card -->
        </div>
    </div>
@endsection

@section('script')
    <script type="text/javascript">
        $(document).ready(function() {
            "use strict";
            var table = $('.table_top_content');
            table.DataTable({
                "dom": '<<"" <"dataTable_top left col-xs col-sm-12 col-md-6 col-lg-6 col-xl-6 pl-0"i<"clear">> <"dataTable_top right col-xs col-sm-12 col-md-6 col-lg-6 col-xl-6 pr-0"f<"clear">> >rt<"bottom"p<"clear">>',
                "oLanguage": { "sSearch": "" }
            });
        });
    </script>
    @endsection

resources/views/adminPanel/student/show.blade.php
@extends('adminPanel.layouts.main')
@section('content')
    <!-- ////////// Page Title & Breadcrumbs //////////-->
    <div class="row">
        <div class="col-xs col-sm-12 col-md-12 col-lg-12 col-xl-12">
            <h4>students</h4>
            <nav class="breadcrumb">
                <a class="breadcrumb-item" href="{{route('index')}}">Home</a>
                <a class="breadcrumb-item" href="{{route('student.index')}}">students</a>
                <span class="breadcrumb-item active">student {{$student->name}}</span>
            </nav> <!-- /breadcrumb -->
        </div> <!-- /col -->
    </div> <!-- /row -->

    <div class="row">

        <!-- ////////// Basic DataTable //////////-->
        <div class="col-xs col-sm-12 col-md-12 col-lg-12 col-xl-12 mt-4">
            <div class="card">
                <div class="card-heading">
                    <h5>Student {{$student->name}}</h5>
                </div> <!-- /card-heading -->
                <div class="card-body">
                    <table class="table table-striped">
                        <thead>
                        <tr>
                            <th>#</th>
                            <th>#</th>
                        </tr> <!-- /tr -->
                        </thead> <!-- /thead -->
                        <tbody>
                        <tr>
                            <th>Name</th>
                            <td>{{$student->name}}</td>

                        </tr> <!-- /tr -->
                        <tr>
                            <th>Email</th>
                            <td>{{$student->email}}</td>

                        </tr> <!-- /tr -->
                        <tr>
                            <th >Phone</th>
                            <td>{{$student->phone}}</td>
                        </tr>
                        <tr>
                            <td>image</td>
                            <td>{!! Html::image($student->image,'',['class'=>'img-responsive','width'=>'250px','height'=>'250px']) !!}</td>
                        </tr>
                        <tr>
                            <td>attends</td>
                            <td><a href="{{route('studentAttend',['id'=>$student->uuid])}}"><i class="fa fa-leanpub"></i></a></td>
                        </tr>
                        <tr>
                            <td>Reset MAC</td>
                            <td><a href="{{route('studentMAC',['id'=>$student->uuid])}}">Reset</a></td>
                        </tr>
                        <!-- /tr -->
                        </tbody> <!-- /tbody -->
                    </table> <!-- /table -->
                </div> <!-- /card-body -->
            </div>
        </div>
    </div>
@endsection