routes/admin.php
<?php

Route::get('/home', function () {
    $users[] = Auth::user();
    $users[] = Auth::guard()->user();
    $users[] = Auth::guard('admin')->user();

    //dd($users);

    return view('admin.home');
})->name('home');

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});


Route::view('test','tutor.QR');

Route::group(['prefix' => 'admin'], function () {
    Route::group(['middleware'=>'admin'],function (){
    Route::get('/','AdminPanel\AdminController@index')->name('index');
    Route::resource('student','AdminPanel\studentController');
    Route::resource('tutor','AdminPanel\tutorController');
    Route::resource('admin','AdminPanel\adminUserController');
    Route::resource('lab','AdminPanel\labController');
    Route::post('/password/{id}','AdminPanel\studentController@updatePassword')->name('updatePassword');
    Route::post('/admin/password/{id}','AdminPanel\adminUserController@updatePassword')->name('adminUpdatePassword');
    Route::get('/attend/{id}','AdminPanel\sessionController@attends')->name('attendBySession');
    Route::get('student/attend/{id}','AdminPanel\studentController@attends')->name('studentAttend');
    Route::get('lab/session/{id}','AdminPanel\labController@session')->name('sessionLab');
    Route::get('tutor/session/{id}','AdminPanel\tutorController@session')->name('tutorSession');
    Route::resource('session','AdminPanel\sessionController');
    Route::get('student/MAC/{id}','AdminPanel\studentController@resethMAC')->name('studentMAC');
    Route::get('tutor/MAC/{id}','AdminPanel\tutorController@resetMAC')->name('tutorMAC');

    });


    Route::get('/login', 'AdminAuth\LoginController@showLoginForm')->name('login');
    Route::post('/login', 'AdminAuth\LoginController@login');
    Route::post('/logout', 'AdminAuth\LoginController@logout')->name('logout');
 /*   Route::get('/register', 'AdminAuth\RegisterController@showRegistrationForm')->name('register');
    Route::post('/register', 'AdminAuth\RegisterController@register');*/
    Route::post('/password/email', 'AdminAuth\ForgotPasswordController@sendResetLinkEmail')->name('password.request');
    Route::post('/password/reset', 'AdminAuth\ResetPasswordController@reset')->name('password.email');
    Route::get('/password/reset', 'AdminAuth\ForgotPasswordController@showLinkRequestForm')->name('password.reset');
    Route::get('/password/reset/{token}', 'AdminAuth\ResetPasswordController@showResetForm');
});

Route::group(['middleware'=>'auth:web'],function (){
Route::get('Qr','Qr@index');
Route::get('Qr/session/{id}','Qr@Qr')->name('QR');
Route::get('Qr/refresh/{id}','Qr@refresh')->name('QrRefresh');
});
Route::view('notTutor','tutor.ForTutorOnly');
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

Route::get('/home', 'HomeController@index')->name('home');

app/Session.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Session extends Model
{
    /*'id', 'courseName', 'labID', 'token', 'TutorsID', 'time', 'notes'*/
    //
    protected $fillable=[ 'courseName', 'labID', 'token', 'TutorID', 'time', 'notes'];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    function lab(){
        return $this->belongsTo('App\Location','labID','id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    function doctor(){
        return $this->belongsTo('App\User','TutorID','uuid');
    }
}

app/Http/Controllers/API/SessionController.php
<?php

namespace App\Http\Controllers\API;

use App\Http\Controllers\Controller;
use App\Session;
use Illuminate\Http\Request;
use Validator;

class   SessionController extends Controller
{
    function __construct()
    {
        $this->middleware('TutorsOnly')->only(['store']);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return response()->json(['sessions'=>Session::with('doctor','lab')->get()],200);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $rules = ['courseName' => 'required', 'labID' => 'required','time'=>'date','notes'=>'string'];
        $validator = Validator::make($request->all(), $rules);
        if ($validator->fails()) {
            return response(['status' => false, 'message' => $validator->messages()]);

        } else {
            $session=Session::create($request->all() + ['TutorID'=>auth()->user()->uuid,'token'=>str_random(50)]);
            return response()->json(['session'=>$session]);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return response()->json(['session'=>Session::with('doctor','lab')->where('id',$id)->first()]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    /**
     * @param Request $request
     * @return \Illuminate\Http\JsonResponse
     */
    public function SessionByDate(Request $request){
        return response()->json(['sessions'=>Session::with('doctor','lab')->whereDate('time',$request['date'])->orderBy('time','asc')->get()]);
    }

    /**
     * @param Request $request
     * @return \Illuminate\Http\JsonResponse
     */
    public function SessionTutorByDate(Request $request){
        return response()->json(['sessions'=>Session::with('doctor','lab')->whereDate('time',$request['date'])->where('TutorID',auth()->user()->uuid)->get()]);
    }
}

app/Http/Controllers/AdminPanel/AdminController.php
<?php

namespace App\Http\Controllers\AdminPanel;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class AdminController extends Controller
{
    public function index()
    {
        return view('adminPanel.index');
    }
}

app/Http/Controllers/AdminPanel/adminUserController.php
<?php

namespace App\Http\Controllers\AdminPanel;

use Alert;
use App\Admin;
use App\Http\Controllers\Controller;
use App\Http\Requests\addAdmin;
use App\Http\Requests\updatePassword;
use Illuminate\Http\Request;

class adminUserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('adminPanel.admin.index')->with('admins',Admin::all());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('adminPanel.admin.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(addAdmin $request)
    {
        Admin::create($request->except('password') + ['password'=>bcrypt($request['password'])]);
        alert()->success('Success Message')->autoclose(1000);
        return back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return view('adminPanel.admin.edit')->with('admin',Admin::where('id',$id)->first());
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $user=Admin::where('id',$id)->first();
        $user->update($request->only('name'));
        alert()->success('Success Message')->autoclose(1000);
        return back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function updatePassword(updatePassword $request,$id)
    {
        $user = Admin::where('id', $id)->first();
        $user->update(['password' => bcrypt($request['password'])]);
        Alert::success('Password Edified Successfully !')->persistent('Close');
        return back();
    }

}

app/Http/Controllers/AdminPanel/labController.php
<?php

namespace App\Http\Controllers\AdminPanel;

use App\Http\Controllers\Controller;
use App\Http\Requests\labAdd;
use App\Location;
use Illuminate\Http\Request;
use App\Session;

class labController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('adminPanel.lab.index')->with('labs', Location::all());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('adminPanel.lab.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(labAdd $request)
    {
        Location::create($request->all());
        alert()->success('Success Message', 'Optional Title')->autoclose(1000);
        return back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return view('adminPanel.lab.show')->with('lab',Location::find($id));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return view('adminPanel.lab.edit')->with('lab',Location::find($id));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(labAdd $request, $id)
    {
        Location::find($id)->update($request->all());
        alert()->success('Success Message', 'Optional Title')->autoclose(1000);
        return back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function session($id){
        return view('adminPanel.session.index')->with('sessions',Session::with('lab','doctor')->where('labID',$id)->get());
    }
}

app/Http/Controllers/AdminPanel/sessionController.php
<?php

namespace App\Http\Controllers\AdminPanel;

use App\Attend;
use App\Http\Controllers\Controller;
use App\Session;
use Illuminate\Http\Request;

class sessionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('adminPanel.session.index')->with('sessions',Session::with('lab','doctor')->get());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return view('adminPanel.session.show')->with('session',Session::with('lab','doctor')->where('id',$id)->first());
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Session::find($id)->delete();
        alert()->success('Success Message', 'Optional Title')->autoclose(1000);
        return back();
    }

    public function attends($id)
    {
        return view('adminPanel.attends.index')->with('attends',Attend::where('SessionID',$id)->with('session')->get());
    }
}

resources/views/adminPanel/session/index.blade.php
@extends('adminPanel.layouts.main')
@section('content')
    <!-- ////////// Page Title & Breadcrumbs //////////-->
    <div class="row">
        <div class="col-xs col-sm-12 col-md-12 col-lg-12 col-xl-12">
            <h4>sessions</h4>
            <nav class="breadcrumb">
                <a class="breadcrumb-item" href="#">Home</a>
                <span class="breadcrumb-item active">sessions</span>
            </nav> <!-- /breadcrumb -->
        </div> <!-- /col -->
    </div> <!-- /row -->

    <div class="row">

        <!-- ////////// Basic DataTable //////////-->
        <div class="col-xs col-sm-12 col-md-12 col-lg-12 col-xl-12 mt-4">
            <div class="card">
                <div class="card-heading">
                </div> <!-- /card-heading -->
                <div class="card-body">

                    <table id="basic_table" class="table_top_content table table-responsive table-striped">
                        <thead>
                        <tr>
                            <th>Course Name</th>
                            <th>lab</th>
                            <th>tutor</th>
                            <th>time</th>
                            <th>Action</th>
                        </tr> <!-- /tr -->
                        </thead> <!-- /thead -->
                        <tbody>
                        @foreach($sessions as $key=> $session)
                        <tr>
                            <td>{{$session->courseName}}</td>
                            <td>{{$session->lab->name}}</td>
                            <td>{{$session->doctor->name}}</td>
                            <td>{{$session->time}}</td>
                            <td>
                                <a href="{{route('session.show',['id'=>$session->id])}}"><i class="fa fa-eye"></i></a>
                                &nbsp;
                                <a onclick="$('#{{$key}}delete').submit()"><i class="fa fa-trash"></i> </a>
                                {!! Form::open(['url'=>route('session.destroy',['id'=>$session->id]),'method'=>'delete','id'=>$key.'delete']) !!}
                                {!! Form::close() !!}
                            </td>
                        </tr>
                        @endforeach

                        </tbody> <!-- /tbody -->
                        <tfoot>
                        <tr>
                            <th>Course Name</th>
                            <th>lab</th>
                            <th>tutor</th>
                            <th>time</th>
                            <th>Action</th>
                        </tr> <!-- /tr -->
                        </tfoot> <!-- /tfoot -->
                    </table> <!-- /table-responsive -->
                </div> <!-- /card-body -->
            </div> <!-- /card -->
        </div>
    </div>
@endsection

@section('script')
    <script type="text/javascript">
        $(document).ready(function() {
            "use strict";
            var table = $('.table_top_content');
            table.DataTable({
                "dom": '<<"" <"dataTable_top left col-xs col-sm-12 col-md-6 col-lg-6 col-xl-6 pl-0"i<"clear">> <"dataTable_top right col-xs col-sm-12 col-md-6 col-lg-6 col-xl-6 pr-0"f<"clear">> >rt<"bottom"p<"clear">>',
                "oLanguage": { "sSearch": "" }
            });
        });
    </script>
    @endsection

resources/views/adminPanel/session/show.blade.php
@extends('adminPanel.layouts.main')
@section('content')
    <!-- ////////// Page Title & Breadcrumbs //////////-->
    <div class="row">
        <div class="col-xs col-sm-12 col-md-12 col-lg-12 col-xl-12">
            <h4>sessions</h4>
            <nav class="breadcrumb">
                <a class="breadcrumb-item" href="{{route('index')}}">Home</a>
                <a class="breadcrumb-item" href="{{route('session.index')}}">sessions</a>
                <span class="breadcrumb-item active">session {{$session->name}}</span>
            </nav> <!-- /breadcrumb -->
        </div> <!-- /col -->
    </div> <!-- /row -->

    <div class="row">

        <!-- ////////// Basic DataTable //////////-->
        <div class="col-xs col-sm-12 col-md-12 col-lg-12 col-xl-12 mt-4">
            <div class="card">
                <div class="card-heading">
                    <h5>session {{$session->name}}</h5>
                </div> <!-- /card-heading -->
                <div class="card-body">
                    <table class="table table-striped">
                        <thead>
                        <tr>
                            <th>#</th>
                            <th>#</th>
                        </tr> <!-- /tr -->
                        </thead> <!-- /thead -->
                        <tbody>
                        <tr>
                            <th>Course Name</th>
                            <td>{{$session->courseName}}</td>

                        </tr> <!-- /tr -->
                        <tr>
                            <th>lab</th>
                            <td>{{$session->lab->name}}</td>

                        </tr> <!-- /tr -->
                        <tr>
                            <th >tutor</th>
                            <td>{{$session->doctor->name}}</td>
                        </tr>
                        <tr>
                            <td>time</td>
                            <td>{{$session->time}}</td>
                        </tr>
                        <tr>
                            <td>Attends</td>
                            <td><a href="{{route('attendBySession',['id'=>$session->id])}}"><i class="fa fa-book"></i></a></td>
                        </tr>
                        <!-- /tr -->
                        </tbody> <!-- /tbody -->
                    </table> <!-- /table -->
                </div> <!-- /card-body -->
            </div>
        </div>
    </div>
@endsection